---
title: "Data Products with Leaflet"
author: "Enrique Repullés"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Date:10/07/2017 

## Description

In the city of Barcelona, the town hall publishes a web page with a lot of data sources about the city. The web page is: [http://opendata-ajuntament.barcelona.cat/en/]

I've selected a data source about traffic accidents. I show the accident location in the map, along with the date, number of deaths and injured.

The source of this document can be found at [https://github.com/enrique-repulles/data-products-leaflet]

## Map: traffic accidents in Barcelona, year 2016


```{r data processing}

# Data downloading: 
url<-"http://opendata-ajuntament.barcelona.cat/data/dataset/e769eb9d-d778-4cd7-9e3a-5858bba49b20/resource/be253540-d3ec-418f-9b72-386492fa5269/download/2016_accidents_gu_bcn_.csv"

dfnames<-c(
"record.number","distrinct.code","district.name","quarter.code","quarter.name",
"street.code","street.name","street.number","week.day.name","week.day","day.type",
"year","month","month.name","month.day","hour","shift","cause.description.pedestrian",
"fatalities","minor.injuries","serious.injuries","vehicles.involved","utm.x","utm.y",
"long","lat")

df <- read.csv(url,col.names = dfnames)
```


```{r map construction}

library(leaflet)
# I remove some wrong points with large latitude / longitude
df<-df[df$long<100,]
df<-df[df$lat<100,]

markers <- data.frame (longitude=df$long, latitude=df$lat)

popuptext <- paste("<b>date: ", df$month.day,"/",df$month,"/",df$year,"</b>",
                   "<br/> deaths: ",df$fatalities,
                   "<br/> serious injuries: ",df$serious.injuries,
                   "<br/> minor injuries: ",df$minor.injuries
                   )

map <- leaflet(data = markers ) %>%  addTiles()  %>% 
    addMarkers(popup = popuptext, clusterOptions=markerClusterOptions()) 
```

```{r map plot, echo=FALSE}
map
```
